### ISSUE TITLE
enable "Cloudwatch Logs" service=logs  

### ISSUE THREAD

**Issue by dhagan-va** [localstack/localstack-java-utils#11]
What a cool -project and it is working well for me.  Nice work!

I do not see service logs in  public class ServiceName {}  "Cloudwatch Logs" is supported in localstack on the default port 4586.  Is this something that could be easily enabled?

**Comment by whummer** [comment]
Hi @dhagan-va , thanks for suggesting this improvement. Do you think you could contribute a small pull request to add the missing functionality? That would be much appreciated - thanks!

**Comment by dhagan-va** [comment]
Hi @whummer  could you give me a handrail/sketch of what I would need to change and I might give it a shot?  Thank you!

**Comment by ceejaey** [comment]
@whummer, 
I've done a possible implementation of this to submit for review, 
but I'm not sure how do you tend to approach version numbering of the POM file, would you like this incremented as a minor version?

**Comment by whummer** [comment]
Hi @ceejaey , that sounds great - looking forward to reviewing the change. Yes, if you could please increment the minor version number for this change (and add a short note to the change log in the README), then we can release a new version right away. Thanks!

**Comment by whummer** [comment]
Fixed in #18 - thanks!
