### ISSUE TITLE
Docker executable not found in Windows 10

### ISSUE THREAD

**Issue by jorgenota** [localstack/localstack-java-utils#24]
When trying to execute a JUnit 5 test using the `LocalstackDockerExtension`, I'm getting an IllegalStateException with the message "Cannot find docker executable."

I've been debugging the issue and found that DockerExe class has a constant (`POSSIBLE_EXE_LOCATIONS`) with the possible locations to find the executable. It contain 3 possible paths:
- "C:/program files/docker/docker/resources/bin/docker.exe"
- "/usr/local/bin/docker"
- "/usr/bin/docker"

However, neither of them matches the path of my docker executable. I've recently installed docker and the executable is in:
- "C:\ProgramData\DockerDesktop\version-bin\docker.exe"

... this is not the real location, but a simbolinc link... the actual location is:
- "C:\Program Files\Docker\Docker\resources\docker.exe"

**Additional information:**
The change of location is probably a recent change in Docker. I've even found a recent bug in docker 2.3.4.0 related to this change: https://github.com/docker/for-win/issues/7898

**Possible solution/improvement:**
I guess the constant should be updated with the new path ("C:\Program Files\Docker\Docker\resources\docker.exe").

**Comment by jorgenota** [comment]
By the way, in case it might be useful, in the meantime I've found to make it work creating a simbolic link:
mklink "C:/program files/docker/docker/resources/bin/docker.exe" "C:\ProgramData\DockerDesktop\version-bin\docker.exe"

**Comment by whummer** [comment]
Many thanks for reporting this issue and contributing a fix @jorgenota ! A new version `0.2.6` of the Java libs has now been released to Maven Central. 👍
