### ISSUE TITLE
Configure port binding behaviour

### ISSUE THREAD

**Issue by Madh93** [localstack/localstack-java-utils#31]
Hi,

Is there any plan to configure the Docker port binding behaviour using the `@LocalstackDockerProperties` annotation? Right now the LocalStack edge and elastic ports are harcoded:

https://github.com/localstack/localstack-java-utils/blob/master/src/main/java/cloud/localstack/docker/Container.java#L24
https://github.com/localstack/localstack-java-utils/blob/master/src/main/java/cloud/localstack/docker/Container.java#L25

**Comment by whummer** [comment]
Thanks again for the PR @Madh93 - this has now been published to Maven Central as version `0.2.7` of the library. Thanks
