### ISSUE TITLE
Allow to mount files to the container started through @LocalstackDockerProperties

### ISSUE THREAD

**Issue by cbromberg** [localstack/localstack-java-utils#41]
Hi,

I have been able to migrate a project of decent size from running ElasticSearch locally and DynamoDbLocal to localstack and it works great 🥇  - we were able to drop implementation classes that we used to replace S3 with files locally 💯 

I have the setup code for the resources created in a dev-profile bean in the app and I would like to remove that because I have to add extra dependencies to the classpath to make that code work. localstack has the right mechanism for that - the init scripts. So I would like to create a PR for allowing the Java code set the mount parameter for the init scripts as well, that way we can remove the initialization Java code. I imagine that that is not a huge amount of code that needs to be written in localstack-java-utils as it only exposes existing functionality of the localstack container.
Would you welcome that feature / PR as well?
Cheers, Chris

**Comment by whummer** [comment]
Hi @cbromberg - thanks for the feedback. Absolutely, that change would be extremely useful and much appreciated! Looking forward to it - thanks for your help.

**Comment by whummer** [comment]
Added in #46 - thanks again!

**Comment by cbromberg** [comment]
Thanks for the quick release as well 🎉
