### ISSUE TITLE
Failure to detect localstack start due to multiple errors in the logs

### ISSUE THREAD

**Issue by AntonOellerer** [localstack/localstack-java-utils#80]
Hey,
It seems as if in one of the last localstack nightly versions a change was introduced which causes the container to throw a large amount of error messages like
```
2021-11-10T12:16:46:DEBUG:stevedore.extension: found extension EntryPoint(name='sagemaker:pro', value='localstack_ext.services.providers:sagemaker', group='localstack.aws.provider')
2021-11-10T12:16:46:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='sagemaker:pro', value='localstack_ext.services.providers:sagemaker', group='localstack.aws.provider'): No module named 'localstack_ext.services.providers'
```
This in turn causes `localstack-java-utils` to fail to detect the container startup, since the `Ready.` token is further up in the logs than the last 100 fetched lines.

When starting the image up by hand, those errors are not thrown.
The only properties I used were `useSingleDockerContainer = true`, I am using podman instead of docker though.
Do you know where the problem could be?
Related, is there some image tag such as `stable`? It seems strange that I always need to fetch the `latest` version if I don't want to specify a certain image.

[localstack.log](https://github.com/localstack/localstack-java-utils/files/7512603/localstack.log)

**Comment by sanimalp** [comment]
You can use the following tag to specify which localstack version you want to use: `imageTag = "0.12.19.1"`

**Comment by AntonOellerer** [comment]
Yes, but now if a new stable version gets release, I have to change it everywhere, instead of it getting updated automatically as if there were a tag such as `stable`.
I also read a proposal something which suggested using a `nightly` tag for the nightlies and `latest` for the stable versions.

**Comment by smalga** [comment]
We're also encountering this issue across our Jenkins builds and I don't really want to hard code specific imageTag versions across our tests/repos unless they are something like `stable`.
If the multiple errors on startup can't be resolved quickly then a very simple fix would be to increase Container.NUM_LOG_LINES so it starts?

**Comment by AntonOellerer** [comment]
Have you checked whether the errors affects the correct execution of the tests?

**Comment by whummer** [comment]
Thanks for reporting @AntonOellerer @sanimalp @smalga  , and apologies for the long delay. This is potentially related to #82 . We believe that this should be fixed in the meantime - a new version `0.2.20` has been pushed to Maven Central. Can you please give it a try with that version? Please let us know if the problem persists.. Thanks!

**Comment by AntonOellerer** [comment]
Works for me, thank you!
Do you know whether the introduction of a `stable` tag is considered?

**Comment by whummer** [comment]
Hi @AntonOellerer , thanks for the pointer - we'll consider introducing a `stable` tag that always points to the latest tagged version (e.g., `0.13.3`) of the image. 👍

**Comment by AntonOellerer** [comment]
Nice, thank you!
