### ISSUE TITLE
Localstack: localStackContainer.waitForLogToken(READY_TOKEN) does not work with LocalStack image version 0.13.0

### ISSUE THREAD

**Issue by Hoagiex** [localstack/localstack-java-utils#82]
```
localstack-utils: 0.2.17
localstack (docker): 0.13.0
os: MacOS Monterey
platform: M1 max (arm)
```

The statement ```localStackContainer.waitForLogToken(READY_TOKEN)``` never completes, because localstack 0.13.0 outputs a lot of log lines and the 'Ready.' token isn't found in the last 100 lines selected in the method
```
    private boolean logContainsPattern(Pattern pattern) {
        String logs = getContainerLogs();
        return pattern.matcher(logs).find();
    }
```

...in the ```cloud.localstack.docker.Container``` class

**Comment by whummer** [comment]
Thanks for reporting @Hoagiex , and apologies for the long delay. This should be fixed in the meantime - a new version `0.2.20` has been pushed to Maven Central. Please keep us posted if the problem persists.. Thanks!
